// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq7ApXGCKcA6KGwj1DKOcPEBc2yD1pI3E',
    appId: '1:77230471128:android:661a508ecb43748e66e4ad',
    messagingSenderId: '77230471128',
    projectId: 'sabbar-1540f',
    storageBucket: 'sabbar-1540f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpNVizrLJ-dRR8clQjKivEWxZTP12Nqo',
    appId: '1:77230471128:ios:dc9c539eebef566b66e4ad',
    messagingSenderId: '77230471128',
    projectId: 'sabbar-1540f',
    storageBucket: 'sabbar-1540f.appspot.com',
    iosClientId: '77230471128-c0stclerr08cc5tna3o48mkk53j5bekj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabbar1',
  );
}
